Suppose Day 1 is a sunny day. What is the probability of the following sequence of 
days: Day2 = cloudy, Day3 = cloudy, Day4 = rainy ?

In [1]:
import random
import numpy as np

In [2]:
# State transition table
transition_table = {
    "Sunny": {"Sunny": 0.8, "Cloudy": 0.2, "Rainy": 0.0},
    "Cloudy": {"Sunny": 0.4, "Cloudy": 0.4, "Rainy": 0.2},
    "Rainy": {"Sunny": 0.2, "Cloudy": 0.6, "Rainy": 0.2}
}

# Initial state means the starting day
current_state = "Sunny"

# Simulate the weather sequence for num_days days
num_days = 7 # You can change this value
for i in range(num_days):
    # Print the current day's weather
    print("Day {}: {}".format(i+1, current_state))
    
    # Transition to the next state based on the probabilities in the transition table
    next_state = random.choices(list(transition_table[current_state].keys()), 
                                list(transition_table[current_state].values()))[0]
    
    # Update the current state for the next iteration
    current_state = next_state


Day 1: Sunny
Day 2: Cloudy
Day 3: Cloudy
Day 4: Cloudy
Day 5: Sunny
Day 6: Cloudy
Day 7: Sunny


Write a simulator that can randomly generate sequences of “weathers” from this state 
transition function.

In [3]:
# Transition matrix
transition_matrix = np.array([[0.8, 0.2, 0.0],
                              [0.4, 0.4, 0.2],
                              [0.2, 0.6, 0.2]])

# Find left eigenvectors of the transition matrix
eigenvalues, eigenvectors = np.linalg.eig(transition_matrix.T)
stationary_vector = np.real(eigenvectors[:, np.isclose(eigenvalues, 1)])

# Reshape stationary_vector to a 2D array with 1 row and 3 columns
stationary_vector = stationary_vector.reshape((1, 3))

# Normalize the stationary vector
stationary_vector = stationary_vector / np.sum(stationary_vector)

# Print the stationary distribution
print("Stationary distribution: Sunny = {:.3f}, Cloudy = {:.3f}, Rainy = {:.3f}"
      .format(stationary_vector[0][0], stationary_vector[0][1], stationary_vector[0][2]))

Stationary distribution: Sunny = 0.643, Cloudy = 0.286, Rainy = 0.071


Use your simulator to determine the stationary distribution of this Markov chain. The 
stationary distribution measures the probability that a random day will be sunny, 
cloud, or rainy?



we can find the stationary distribution of this Markov chain by solving the system of linear equations that define it.

Let π = [π₁, π₂, π₃] be the stationary distribution, where πᵢ represents the probability of being in state i in the long run. We can find the stationary distribution by solving the equation:
πP = π

where P is the state transition matrix. This equation says that the distribution after one step, πP, should be equal to the distribution before the step, π, in the stationary regime.

Expanding this equation, we get a system of linear equations:
π₁(0.8) + π₂(0.4) + π₃(0.2) = π₁
π₁(0.2) + π₂(0.4) + π₃(0.6) = π₂
π₁(0.0) + π₂(0.2) + π₃(0.2) = π₃

Simplifying this system of equations, we get:
0.8π₁ - π₁ = 0
0.4π₁ + 0.4π₂ - π₂ = 0
0.2π₁ + 0.6π₂ + 0.2π₃ - π₃ = 0

We can write this system of equations in matrix form:
[0.8 -1  0] [π₁]   [0]
[0.4  0.4 -1] [π₂] = [0]
[0.2  0.6  0.2] [π₃]   [0]

Solving this system of equations, we get:
π₁ = 4π₃/9
π₂ = 3π₃/8
π₃ = π₃

To find the value of π₃, we use the fact that the stationary distribution must sum to 1, i.e., π₁ + π₂ + π₃ = 1. Substituting the values of π₁ and π₂, we get:
4π₃/9 + 3π₃/8 + π₃ = 1
=> 32π₃ + 27π₃ + 72π₃ = 648
=> 131π₃ = 648
=> π₃ = 648/131

Substituting this value of π₃ into the expressions for π₁ and π₂, we get:
π₁ = 4π₃/9 = 192/393
π₂ = 3π₃/8 = 243/524
π₃ = 648/131

Therefore, the stationary distribution of the Markov chain is:
π = [192/393, 243/524, 648/131] ≈ [0.487, 0.464, 0.049]

In [5]:
# Identity matrix
identity_matrix = np.eye(3)

# Calculate the stationary distribution
_, _, v = np.linalg.svd(transition_matrix.T - identity_matrix)
stationary_vector = v[-1, :]
stationary_vector = stationary_vector / np.sum(stationary_vector)

# Print the stationary distribution
print("Stationary distribution: Sunny = {:.3f}, Cloudy = {:.3f}, Rainy = {:.3f}"
      .format(stationary_vector[0], stationary_vector[1], stationary_vector[2]))

Stationary distribution: Sunny = 0.643, Cloudy = 0.286, Rainy = 0.071


Can you devise a closed-form solution to calculating the stationary distribution based 
on the state transition matrix above?

We can calculate the stationary distribution of a Markov chain by finding the eigenvector corresponding to the eigenvalue 1.

In [6]:
# Identity matrix
identity_matrix = np.eye(3)

# Calculate the stationary distribution
eigenvalues, eigenvectors = np.linalg.eig(transition_matrix.T)
index = np.where(np.isclose(eigenvalues, 1))[0][0]  # Find index of eigenvalue 1
stationary_vector = np.real(eigenvectors[:, index])
stationary_vector = stationary_vector / np.sum(stationary_vector)

# Print the stationary distribution
print("Stationary distribution: Sunny = {:.3f}, Cloudy = {:.3f}, Rainy = {:.3f}"
      .format(stationary_vector[0], stationary_vector[1], stationary_vector[2]))

Stationary distribution: Sunny = 0.643, Cloudy = 0.286, Rainy = 0.071


What is the entropy of the stationary distribution ?

 It is calculated using the formula: H = - ∑(p * log2(p))

In [8]:
# Stationary distribution
stationary_distribution = np.array([0.643, 0.286, 0.071])

# Calculate the entropy
entropy = -np.sum(stationary_distribution * np.log2(stationary_vector))

# Print the entropy
print("Entropy of the stationary distribution: {:.3f}".format(entropy))

Entropy of the stationary distribution: 1.197


Using Bayes rule, compute the probability table of yesterday’s weather given today’s weather. It is okay to provide the probabilities numerically, and it is also okay to rely on results from previous questions in this exercise.

we can use the formula:
P(Yesterday | Today) = (P(Today | Yesterday) * P(Yesterday)) / P(Today)

In [9]:
# Today's weather
today_weather = "Cloudy"

# Find the index of today's weather in the list ['Sunny', 'Cloudy', 'Rainy']
today_index = ['Sunny', 'Cloudy', 'Rainy'].index(today_weather)

# Compute the probability table of yesterday's weather given today's weather
yesterday_probabilities = np.zeros(3)
for i, weather in enumerate(['Sunny', 'Cloudy', 'Rainy']):
    yesterday_index = i
    transition_prob = transition_matrix[yesterday_index, today_index]
    yesterday_prob = stationary_distribution[yesterday_index]
    today_prob = np.dot(stationary_distribution, transition_matrix[:, today_index])
    yesterday_given_today_prob = (transition_prob * yesterday_prob) / today_prob
    yesterday_probabilities[yesterday_index] = yesterday_given_today_prob

# Print the probability table
print("Probability table of yesterday's weather given today's weather ({}):".format(today_weather))
print("Sunny: {:.3f}".format(yesterday_probabilities[0]))
print("Cloudy: {:.3f}".format(yesterday_probabilities[1]))
print("Rainy: {:.3f}".format(yesterday_probabilities[2]))


Probability table of yesterday's weather given today's weather (Cloudy):
Sunny: 0.450
Cloudy: 0.401
Rainy: 0.149


Suppose we added seasons to our model. The state transition function above would only apply to the Summer, whereas different ones would apply to Winter, Spring, and Fall. Would this violate the Markov property of this process? Explain your answer.

Yes, adding seasons to the model with different state transition functions for each season would violate the Markov property of the process.

The Markov property states that the future behavior of a stochastic process depends only on its current state and is independent of its past history, given the present state. In other words, the process is memoryless, and the transition probabilities depend only on the current state.

However, in the modified model with seasons, the transition probabilities would depend not only on the current state but also on the current season. This means that the future behavior of the process would no longer be solely determined by the current state but would also be influenced by the current season.

Therefore, by introducing different state transition functions for each season, the process would become dependent on additional information beyond the current state, violating the Markov property.